name: vector_tile_renderer
description: A vector tile renderer for use in creating map tile images or writing to a canvas.
version: 2.1.4
homepage: https://github.com/greensopinion/dart-vector-tile-renderer

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  bezier: ^1.2.0
  vector_math: ^2.1.0
  vector_tile: ^0.3.0

dev_dependencies:
  test: ^1.17.5
